# See https://pre-commit.com for more information
# Pre-commit hooks disabled for research flexibility
ci:
  skip: [pylint, codespell, flake8, ruff, isort, black-jupyter, pyupgrade]
  autofix_prs: false
default_stages: [manual]
repos: []
